[package]
name = "bp-dbc"
version = "0.7.0-alpha.1"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Deterministic bitcoin commitments library"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "bitcoin", "cryptography", "smart-contracts", "single-use-seals"]
categories = ["cryptography::cryptocurrencies", "encoding"]
readme = "../README.md"
edition = "2021"
rust-version = "1.56.1"

[lib]
name = "dbc"
path = "src/lib.rs"

[dependencies]
amplify = "3.12.0"
bitcoin = "0.28.0-rc.2"
secp256k1 = { version = "0.22.1", features = ["global-context"] }
bitcoin_scripts = ">=0.7.0-beta.4"
descriptors = { version = "0.7.0-alpha.1", optional = true }
psbt = { version = "0.7.0-alpha.1", default-features = false, optional = true }
strict_encoding = "1.8.0-rc.7"
commit_verify = ">=0.7.0-alpha.7"
miniscript_crate = { package = "miniscript", version = "7.0.0-rc.2", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }

[features]
default = []
all = ["serde", "miniscript", "consensus", "wallet"]
consensus = []
wallet = ["psbt"]
miniscript = ["miniscript_crate", "bitcoin_scripts/miniscript", "psbt/miniscript", "descriptors"]
serde = ["amplify/serde", "bitcoin/use-serde", "bitcoin_scripts/serde", "commit_verify/serde", "serde_crate", "serde_with"]
